# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyHerzberg(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.HerzbergClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyHerzberg", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.HerzbergClassification"], __result__)

    def ClassifyMaslow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MaslowClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMaslow", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.MaslowClassification"], __result__)

    def ClassifyMcClelland(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.McClellandClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMcClelland", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.McClellandClassification"], __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def GetHerzbergCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetHerzbergCategoricalJustification", llm_response=llm_response, mode="request")
        return typing.cast(types.Suggestion, __result__)

    def GetMaslowCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetMaslowCategoricalJustification", llm_response=llm_response, mode="request")
        return typing.cast(types.Suggestion, __result__)

    def GetMcclellandCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetMcclellandCategoricalJustification", llm_response=llm_response, mode="request")
        return typing.cast(types.Suggestion, __result__)

    def ScoreHerzbergAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.HerzbergQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreHerzbergAnswers", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.HerzbergQuestionAnswerResponse"], __result__)

    def ScoreMaslowAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MaslowQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreMaslowAnswers", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.MaslowQuestionAnswerResponse"], __result__)

    def ScoreMclellandAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.McClellandQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreMclellandAnswers", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.McClellandQuestionAnswerResponse"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyHerzberg(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.HerzbergClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyHerzberg", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.HerzbergClassification"], __result__)

    def ClassifyMaslow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.MaslowClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMaslow", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.MaslowClassification"], __result__)

    def ClassifyMcClelland(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.McClellandClassification"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyMcClelland", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.McClellandClassification"], __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def GetHerzbergCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetHerzbergCategoricalJustification", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Suggestion, __result__)

    def GetMaslowCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetMaslowCategoricalJustification", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Suggestion, __result__)

    def GetMcclellandCategoricalJustification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Suggestion:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetMcclellandCategoricalJustification", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Suggestion, __result__)

    def ScoreHerzbergAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.HerzbergQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreHerzbergAnswers", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.HerzbergQuestionAnswerResponse"], __result__)

    def ScoreMaslowAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.MaslowQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreMaslowAnswers", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.MaslowQuestionAnswerResponse"], __result__)

    def ScoreMclellandAnswers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.McClellandQuestionAnswerResponse"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreMclellandAnswers", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.McClellandQuestionAnswerResponse"], __result__)

    