# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (14)
# #########################################################################

class HerzbergClassification(BaseModel):
    question: typing.Optional[str] = None
    classification: typing.List[types.HerzbergCategory]

class HerzbergQuestionAnswerPair(BaseModel):
    question: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.HerzbergCategory]
    choices: typing.List[str]

class HerzbergQuestionAnswerResponse(BaseModel):
    question: typing.Optional[str] = None
    score: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.HerzbergCategory]

class ListQuestion(BaseModel):
    question: typing.Optional[str] = None
    options: typing.List[str]

class MaslowClassification(BaseModel):
    question: typing.Optional[str] = None
    classification: typing.List[types.MaslowCategory]

class MaslowQuestionAnswerPair(BaseModel):
    question: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.MaslowCategory]
    choices: typing.List[str]

class MaslowQuestionAnswerResponse(BaseModel):
    question: typing.Optional[str] = None
    score: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.MaslowCategory]

class McClellandClassification(BaseModel):
    question: typing.Optional[str] = None
    classification: typing.List[types.McClellandCategory]

class McClellandQuestionAnswerPair(BaseModel):
    question: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.McClellandCategory]
    choices: typing.List[str]

class McClellandQuestionAnswerResponse(BaseModel):
    question: typing.Optional[str] = None
    score: typing.Optional[str] = None
    answer: typing.Optional[str] = None
    category: typing.List[types.McClellandCategory]

class QuestionSuggestion(BaseModel):
    question: typing.Optional[str] = None
    questionType: typing.Optional[types.QuestionType] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class Suggestion(BaseModel):
    recommendation: typing.Optional[str] = None
    suggestedQuestions: typing.List["QuestionSuggestion"]

class TextQuestion(BaseModel):
    question: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
