# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def ClassifyHerzberg(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.HerzbergClassification"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyHerzberg(questions=questions,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyHerzberg", args={
                "questions": questions,
            })
            return typing.cast(typing.List["types.HerzbergClassification"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyMaslow(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MaslowClassification"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyMaslow(questions=questions,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyMaslow", args={
                "questions": questions,
            })
            return typing.cast(typing.List["types.MaslowClassification"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyMcClelland(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.McClellandClassification"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyMcClelland(questions=questions,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyMcClelland", args={
                "questions": questions,
            })
            return typing.cast(typing.List["types.McClellandClassification"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetHerzbergCategoricalJustification(self, questions: typing.List[str],category: types.HerzbergCategory,
        baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetHerzbergCategoricalJustification(questions=questions,category=category,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetHerzbergCategoricalJustification", args={
                "questions": questions,"category": category,
            })
            return typing.cast(types.Suggestion, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetMaslowCategoricalJustification(self, questions: typing.List[str],category: types.MaslowCategory,
        baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetMaslowCategoricalJustification(questions=questions,category=category,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetMaslowCategoricalJustification", args={
                "questions": questions,"category": category,
            })
            return typing.cast(types.Suggestion, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetMcclellandCategoricalJustification(self, questions: typing.List[str],category: types.McClellandCategory,
        baml_options: BamlCallOptions = {},
    ) -> types.Suggestion:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetMcclellandCategoricalJustification(questions=questions,category=category,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetMcclellandCategoricalJustification", args={
                "questions": questions,"category": category,
            })
            return typing.cast(types.Suggestion, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ScoreHerzbergAnswers(self, pairs: typing.List["types.HerzbergQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.HerzbergQuestionAnswerResponse"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ScoreHerzbergAnswers(pairs=pairs,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ScoreHerzbergAnswers", args={
                "pairs": pairs,
            })
            return typing.cast(typing.List["types.HerzbergQuestionAnswerResponse"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ScoreMaslowAnswers(self, pairs: typing.List["types.MaslowQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MaslowQuestionAnswerResponse"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ScoreMaslowAnswers(pairs=pairs,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ScoreMaslowAnswers", args={
                "pairs": pairs,
            })
            return typing.cast(typing.List["types.MaslowQuestionAnswerResponse"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ScoreMclellandAnswers(self, pairs: typing.List["types.McClellandQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.McClellandQuestionAnswerResponse"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ScoreMclellandAnswers(pairs=pairs,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ScoreMclellandAnswers", args={
                "pairs": pairs,
            })
            return typing.cast(typing.List["types.McClellandQuestionAnswerResponse"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyHerzberg(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.HerzbergClassification"], typing.List["types.HerzbergClassification"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyHerzberg", args={
            "questions": questions,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.HerzbergClassification"], typing.List["types.HerzbergClassification"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.HerzbergClassification"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.HerzbergClassification"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyMaslow(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.MaslowClassification"], typing.List["types.MaslowClassification"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyMaslow", args={
            "questions": questions,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.MaslowClassification"], typing.List["types.MaslowClassification"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.MaslowClassification"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.MaslowClassification"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyMcClelland(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.McClellandClassification"], typing.List["types.McClellandClassification"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyMcClelland", args={
            "questions": questions,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.McClellandClassification"], typing.List["types.McClellandClassification"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.McClellandClassification"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.McClellandClassification"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetHerzbergCategoricalJustification(self, questions: typing.List[str],category: types.HerzbergCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetHerzbergCategoricalJustification", args={
            "questions": questions,"category": category,
        })
        return baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion](
          __result__,
          lambda x: typing.cast(stream_types.Suggestion, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Suggestion, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetMaslowCategoricalJustification(self, questions: typing.List[str],category: types.MaslowCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetMaslowCategoricalJustification", args={
            "questions": questions,"category": category,
        })
        return baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion](
          __result__,
          lambda x: typing.cast(stream_types.Suggestion, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Suggestion, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetMcclellandCategoricalJustification(self, questions: typing.List[str],category: types.McClellandCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetMcclellandCategoricalJustification", args={
            "questions": questions,"category": category,
        })
        return baml_py.BamlSyncStream[stream_types.Suggestion, types.Suggestion](
          __result__,
          lambda x: typing.cast(stream_types.Suggestion, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Suggestion, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ScoreHerzbergAnswers(self, pairs: typing.List["types.HerzbergQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.HerzbergQuestionAnswerResponse"], typing.List["types.HerzbergQuestionAnswerResponse"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ScoreHerzbergAnswers", args={
            "pairs": pairs,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.HerzbergQuestionAnswerResponse"], typing.List["types.HerzbergQuestionAnswerResponse"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.HerzbergQuestionAnswerResponse"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.HerzbergQuestionAnswerResponse"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ScoreMaslowAnswers(self, pairs: typing.List["types.MaslowQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.MaslowQuestionAnswerResponse"], typing.List["types.MaslowQuestionAnswerResponse"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ScoreMaslowAnswers", args={
            "pairs": pairs,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.MaslowQuestionAnswerResponse"], typing.List["types.MaslowQuestionAnswerResponse"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.MaslowQuestionAnswerResponse"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.MaslowQuestionAnswerResponse"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ScoreMclellandAnswers(self, pairs: typing.List["types.McClellandQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.McClellandQuestionAnswerResponse"], typing.List["types.McClellandQuestionAnswerResponse"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ScoreMclellandAnswers", args={
            "pairs": pairs,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.McClellandQuestionAnswerResponse"], typing.List["types.McClellandQuestionAnswerResponse"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.McClellandQuestionAnswerResponse"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.McClellandQuestionAnswerResponse"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyHerzberg(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyHerzberg", args={
            "questions": questions,
        }, mode="request")
        return __result__
    def ClassifyMaslow(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMaslow", args={
            "questions": questions,
        }, mode="request")
        return __result__
    def ClassifyMcClelland(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMcClelland", args={
            "questions": questions,
        }, mode="request")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    def GetHerzbergCategoricalJustification(self, questions: typing.List[str],category: types.HerzbergCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetHerzbergCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="request")
        return __result__
    def GetMaslowCategoricalJustification(self, questions: typing.List[str],category: types.MaslowCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetMaslowCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="request")
        return __result__
    def GetMcclellandCategoricalJustification(self, questions: typing.List[str],category: types.McClellandCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetMcclellandCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="request")
        return __result__
    def ScoreHerzbergAnswers(self, pairs: typing.List["types.HerzbergQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreHerzbergAnswers", args={
            "pairs": pairs,
        }, mode="request")
        return __result__
    def ScoreMaslowAnswers(self, pairs: typing.List["types.MaslowQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreMaslowAnswers", args={
            "pairs": pairs,
        }, mode="request")
        return __result__
    def ScoreMclellandAnswers(self, pairs: typing.List["types.McClellandQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreMclellandAnswers", args={
            "pairs": pairs,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyHerzberg(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyHerzberg", args={
            "questions": questions,
        }, mode="stream")
        return __result__
    def ClassifyMaslow(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMaslow", args={
            "questions": questions,
        }, mode="stream")
        return __result__
    def ClassifyMcClelland(self, questions: typing.List[typing.Union["types.TextQuestion", "types.ListQuestion"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyMcClelland", args={
            "questions": questions,
        }, mode="stream")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    def GetHerzbergCategoricalJustification(self, questions: typing.List[str],category: types.HerzbergCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetHerzbergCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="stream")
        return __result__
    def GetMaslowCategoricalJustification(self, questions: typing.List[str],category: types.MaslowCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetMaslowCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="stream")
        return __result__
    def GetMcclellandCategoricalJustification(self, questions: typing.List[str],category: types.McClellandCategory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetMcclellandCategoricalJustification", args={
            "questions": questions,"category": category,
        }, mode="stream")
        return __result__
    def ScoreHerzbergAnswers(self, pairs: typing.List["types.HerzbergQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreHerzbergAnswers", args={
            "pairs": pairs,
        }, mode="stream")
        return __result__
    def ScoreMaslowAnswers(self, pairs: typing.List["types.MaslowQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreMaslowAnswers", args={
            "pairs": pairs,
        }, mode="stream")
        return __result__
    def ScoreMclellandAnswers(self, pairs: typing.List["types.McClellandQuestionAnswerPair"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScoreMclellandAnswers", args={
            "pairs": pairs,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))