# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (4)
# #########################################################################

class HerzbergCategory(str, Enum):
    Hygiene = "Hygiene"
    Motivator = "Motivator"
    Other = "Other"

class MaslowCategory(str, Enum):
    Physiological = "Physiological"
    Safety = "Safety"
    Belongingness = "Belongingness"
    Esteem = "Esteem"
    SelfActualization = "SelfActualization"
    Other = "Other"

class McClellandCategory(str, Enum):
    Achievement = "Achievement"
    Affiliation = "Affiliation"
    Power = "Power"
    Other = "Other"

class QuestionType(str, Enum):
    Text = "Text"
    Checkbox = "Checkbox"
    RadioGroup = "RadioGroup"
    Dropdown = "Dropdown"

# #########################################################################
# Generated classes (14)
# #########################################################################

class HerzbergClassification(BaseModel):
    question: str
    classification: typing.List[HerzbergCategory]

class HerzbergQuestionAnswerPair(BaseModel):
    question: str
    answer: str
    category: typing.List[HerzbergCategory]
    choices: typing.List[str]

class HerzbergQuestionAnswerResponse(BaseModel):
    question: str
    score: str
    answer: str
    category: typing.List[HerzbergCategory]

class ListQuestion(BaseModel):
    question: str
    options: typing.List[str]

class MaslowClassification(BaseModel):
    question: str
    classification: typing.List[MaslowCategory]

class MaslowQuestionAnswerPair(BaseModel):
    question: str
    answer: str
    category: typing.List[MaslowCategory]
    choices: typing.List[str]

class MaslowQuestionAnswerResponse(BaseModel):
    question: str
    score: str
    answer: str
    category: typing.List[MaslowCategory]

class McClellandClassification(BaseModel):
    question: str
    classification: typing.List[McClellandCategory]

class McClellandQuestionAnswerPair(BaseModel):
    question: str
    answer: str
    category: typing.List[McClellandCategory]
    choices: typing.List[str]

class McClellandQuestionAnswerResponse(BaseModel):
    question: str
    score: str
    answer: str
    category: typing.List[McClellandCategory]

class QuestionSuggestion(BaseModel):
    question: str
    questionType: QuestionType

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class Suggestion(BaseModel):
    recommendation: str
    suggestedQuestions: typing.List["QuestionSuggestion"]

class TextQuestion(BaseModel):
    question: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
