# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.HerzbergClassification": types.HerzbergClassification,
    "stream_types.HerzbergClassification": stream_types.HerzbergClassification,

    "types.HerzbergQuestionAnswerPair": types.HerzbergQuestionAnswerPair,
    "stream_types.HerzbergQuestionAnswerPair": stream_types.HerzbergQuestionAnswerPair,

    "types.HerzbergQuestionAnswerResponse": types.HerzbergQuestionAnswerResponse,
    "stream_types.HerzbergQuestionAnswerResponse": stream_types.HerzbergQuestionAnswerResponse,

    "types.ListQuestion": types.ListQuestion,
    "stream_types.ListQuestion": stream_types.ListQuestion,

    "types.MaslowClassification": types.MaslowClassification,
    "stream_types.MaslowClassification": stream_types.MaslowClassification,

    "types.MaslowQuestionAnswerPair": types.MaslowQuestionAnswerPair,
    "stream_types.MaslowQuestionAnswerPair": stream_types.MaslowQuestionAnswerPair,

    "types.MaslowQuestionAnswerResponse": types.MaslowQuestionAnswerResponse,
    "stream_types.MaslowQuestionAnswerResponse": stream_types.MaslowQuestionAnswerResponse,

    "types.McClellandClassification": types.McClellandClassification,
    "stream_types.McClellandClassification": stream_types.McClellandClassification,

    "types.McClellandQuestionAnswerPair": types.McClellandQuestionAnswerPair,
    "stream_types.McClellandQuestionAnswerPair": stream_types.McClellandQuestionAnswerPair,

    "types.McClellandQuestionAnswerResponse": types.McClellandQuestionAnswerResponse,
    "stream_types.McClellandQuestionAnswerResponse": stream_types.McClellandQuestionAnswerResponse,

    "types.QuestionSuggestion": types.QuestionSuggestion,
    "stream_types.QuestionSuggestion": stream_types.QuestionSuggestion,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Suggestion": types.Suggestion,
    "stream_types.Suggestion": stream_types.Suggestion,

    "types.TextQuestion": types.TextQuestion,
    "stream_types.TextQuestion": stream_types.TextQuestion,


    "types.HerzbergCategory": types.HerzbergCategory,

    "types.MaslowCategory": types.MaslowCategory,

    "types.McClellandCategory": types.McClellandCategory,

    "types.QuestionType": types.QuestionType,

}